{
  "providers": ["..."],
  "nixPkgs": ["nodejs_18", "pnpm", "postgresql"],
  "nixLibs": ["chromium"],
  "nixOverlays": [],
  "phases": {
    "setup": {
      "nixPkgs": ["nodejs_18", "pnpm"]
    },
    "install": {
      "cmds": ["pnpm install --frozen-lockfile"]
    },
    "build": {
      "cmds": [
        "pnpm prisma generate",
        "pnpm build"
      ]
    }
  },
  "start": {
    "cmd": "sh railway-start.sh"
  }
}
